app = "symfony-prometheus"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0

[env]
  APP_ENV="prod"
  APP_RUNTIME='\App\FlySymfonyRuntime'
  MESSENGER_TRANSPORT_DSN='doctrine://default'

[metrics]
  port=9000
  path="/metrics/prometheus"
