controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
        tags: [ 'controller.service_arguments' ]
    type: attribute

app_metrics:
    resource: '@ArtprimaPrometheusMetricsBundle/Resources/config/routing.xml'
